#! /bin/bash

if [[ $1 -eq '-h' ]]
then
    echo "Usage: mergeChannels f1[,f2][,f3] where f1, f2 and f3 are tiff files with single readout greyscale"
else
echo "Merging $1"
    output=$(ImageJ -batch ~/bin/mergeChannels.ijm $1 2> /dev/null)
    eog $output &
    echo "Merged file $output"
fi
